---
document:
  language: en
  type: bachelor
  last-url-check: March 17, 2008
meta:
  title: The Most Important Paper in Existence
  author: John Doe
  subject: Things that matter
  keywords: Big Data, Internet of Things, Buzzwords
  institute: iaas
  number: 12345
  course: se
  examiner: Prof. Dr. Mustermann
  supervisor: Dipl.-Inf. Daniel Düsentrieb
  start-date: January 01, 2016
  end-date: May 01, 2016
  crk: 1.7.2
---
